name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste screenshots here
    validations:
      required: false

  - type: input
    id: home-assistant-version
    attributes:
      label: Home Assistant Version
      description: Settings > About > Core version number
      placeholder: 2025.x.x
    validations:
      required: true

  - type: input
    id: alexa-media-version
    attributes:
      label: Alexa Media Player Version
      description: alexa_media version (from `const.py` or HA startup log)
      placeholder: 5.8.x
    validations:
      required: true

  - type: input
    id: alexapy-version
    attributes:
      label: Alexa Media Player API library Version
      description: alexapy version (from `pip show alexapy` in HA container or HA startup log)
      placeholder: 1.29.x
    validations:
      required: true

  - type: dropdown
    id: two-factor
    attributes:
      label: Have you entered a 52-character key for Amazon 2SV via Authenticator App login?
      description: "Your preferred method must be via Authenticator App. No help will be provided for any authentication issues if you attempt to configure otherwise.\nSee [Enable Two-Step Verification for your Amazon account](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-step-verification-for-your-amazon-account)"
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: alexa-devices
    attributes:
      label: Is the HA core integration Alexa Devices?
      description: "Warning - Running both integrations will undoubtedly cause Amazon to throttle API requests."
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: amazon-domain
    attributes:
      label: Amazon Domain
      description: Which Amazon domain are you using?
      options:
        - amazon.com (US)
        - amazon.co.uk (UK)
        - amazon.de (Germany)
        - amazon.fr (France)
        - amazon.it (Italy)
        - amazon.es (Spain)
        - amazon.nl (Netherlands)
        - amazon.ca (Canada)
        - amazon.com.au (Australia)
        - amazon.co.jp (Japan)
        - amazon.in (India)
        - amazon.com.br (Brazil)
        - amazon.com.mx (Mexico)
        - Other
    validations:
      required: true

  - type: input
    id: amazon-domain-other
    attributes:
      label: Amazon Domain (if Other)
      description: If you selected "Other" above, please specify which Amazon domain you're using
      placeholder: e.g., amazon.se, amazon.pl
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Debug Logs (alexa_media & alexapy)
      description: |
        Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component) if this is a functional issue.
        Logs are especially helpful for login issues, device discovery problems, or unexpected errors.
        For large logs, you can drag-and-drop a file here or use a pastebin service.
      placeholder: Paste relevant log excerpts here, or attach log file
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any other relevant information
    validations:
      required: false
