# https://github.com/roots/issue-closer-action
name: Autocloser
on:
  issues:
    types:
      # If you want the duplicate URL checker and/or the auto-closer
      - opened
      # If you want the auto-closer to run
      - edited
      - reopened
  issue_comment:
    types:
      - created
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Autoclose issues that did not follow issue template
        uses: roots/issue-closer@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: "@${issue.user.login} this issue was automatically closed because it did not follow the [issue template](https://github.com/alandtse/alexa_media_player/issues/new/choose) and this warning: **IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**"
          issue-pattern: ".*(Please search the issues, including closed issues,|Describe the bug|Home-assistant \\(version\\)|For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA|Is your feature request related to a problem)"
